version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: internal-mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/init:/docker-entrypoint-initdb.d
      - mongo_data:/data/db

  discovery-server:
    build: ./discovery_server
    container_name: discovery-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api_gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server

  auth-service:
    build: ./auth
    container_name: auth-service
    depends_on:
      - discovery-server
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://internal-mysql:3306/auth
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver

  product-service:
    build: ./product
    container_name: product-service
    depends_on:
      - discovery-server
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/products

volumes:
  mysql_data:
  mongo_data:
