spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?createDatabaseIfNotExist=true
    username: root
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}