spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/auth
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret-key: thisislekybasecretkey15042005hehe
    expiration: 360000000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id:
