spring:
  datasource:
    username: root
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret-key: ${SPRING_JWT_SECRET_KEY}
    expiration: 360000

server:
  port: 0
  servlet:
    context-path: /auth-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}